spring.application.name=skistation
spring.datasource.url=jdbc:mysql://localhost:3306/skistation
spring.datasource.username=skistation_user
spring.datasource.password=skistation123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect